ruby:
  config_file: .rubocop.yml
javascript:
  enabled: false
coffeescript:
  enabled: false
jscs:
  enabled: false
eslint:
  enabled: false
scss:
  enabled: false
haml:
  enabled: false
go:
  enabled: false
python:
    enabled: false
swift:
  enabled: false
fail_on_violations: true
